# Generated by Django 4.0.4 on 2022-04-23 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipeApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='recipe_ingredient',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
