# Generated by Django 4.0.4 on 2022-04-24 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipeApp', '0003_recipe_recipe_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='recipe_ingredient',
            field=models.TextField(),
        ),
    ]
