# Generated by Django 4.0.4 on 2022-04-25 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipeApp', '0004_alter_recipe_recipe_ingredient'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='author',
            new_name='recipe_author',
        ),
    ]
