# Generated by Django 4.0.4 on 2022-05-17 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0002_user_create_at_user_updated_at'),
        ('recipeApp', '0005_rename_author_recipe_recipe_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='favorited_by',
            field=models.ManyToManyField(related_name='favorited_recipes', to='userApp.user'),
        ),
    ]
